sudo: required
addons:
  apt:
    update: true
    packages:
      - docker-ce
services:
  - docker
script:
  - export DOCKER_CLI_EXPERIMENTAL=enabled
  - source sha_functions.sh
  - node_x86_sha=$(get_variant_sha "node" "alpine3.11" "amd64")
  - echo $node_x86_sha
  - treehouses_node_x86_sha=$(get_manifest_sha "treehouses/node" "amd64")
  - echo $treehouses_node_x86_sha
  - node_arm_sha=$(get_tag_sha "balenalib/raspberry-pi-alpine-node" "latest")
  - echo $node_arm_sha
  - treehouses_node_arm_sha=$(get_manifest_sha "treehouses/alpine-node" "arm")
  - echo $treehouses_node_arm_sha
  - node_arm64_sha=$(get_variant_sha "node" "alpine3.11" "arm64")
  - echo $node_arm64_sha
  - treehouses_node_arm64_sha=$(get_manifest_sha "treehouses/node" "arm64")
  - echo $treehouses_node_arm64_sha
  - flag=$(compare_sha  "$node_x86_sha" "$treehouses_node_x86_sha" "$node_arm_sha" "$treehouses_node_arm_sha" "$node_arm64_sha" "treehouses_node_arm64_sha")
  - echo $flag
  - echo $DOCKERAPIKEY | docker login -u "sevenseas" --password-stdin
#before_deploy:
#  - tag="3.11-$(date +%Y%m%d%H%M)"
#  - echo $tag
#  - create_manifests treehouses/node $tag  "node@"$node_x86_sha "balenalib/raspberry-pi-alpine-node@"$node_arm_sha "node@"$node_arm64_sha
#  - docker manifest inspect treehouses/node:latest
#  - docker manifest inspect treehouses/node:$tag
#deploy:
#  - provider: script
#    script: docker manifest push treehouses/node:$tag; docker manifest push treehouses/node:latest
#    skip_cleanup: true
#    on:
#      all_branches: true
#      condition: $flag = true
env:
  global:
    secure: "Wn30B3o7kDa8HGVy2RmQbSNEiWDhBSyV66xHee3hv1HPtSb8Obc7VNmYQQAMho076oD/8yrqPtHofYQcS9DxWUyLTwk6HsJCYSvwsJR5MGq48jQ3rDc7wml/rAiZNzxezzFrHwJAGCToSW+aueG7jpIJeepRMufSIchnHwcaK8b1inC8gRHlJNBW8tzQrp4sC8rRfHAo4S3VxqmmtpTleHjZpC0/ji04aLMKbGS0PdpOKd4EVvOmtj/EaPExYU6lAZDtIgZe27ebX2Dp1MT6L3OvoznuBEyoJXJRsZJTa3R2ohZZW9LlP1XPkN+aloCZtVLVxNcwEpiZ/+FCfBnnS2w93WoamjzLY2KgsNQKeAwq5AP9GGu8GOo7ZIvtOoHvqIo5FhlQIfLKvWa333IVtlBQiUj6ze8/1fdHbKuyr7X1N8YWmsMGMUxSZK0HE2+qL43bz8oncTYLdZrbNf1ru3PcRjwDmhauNo2rHOamug/BZMPeHJcsjDiReyknyEL8kYAALPEy8BkRVV5rSOzomvAbpNUflFWzqKCKAGHoaf91lOY9w69EHW7X5nLfcOAYBto7YH5fK1nVsqMKcb9HeLuG0b3WRKTWpvz/HHzKSs0LjDehL3unCLndJ+3fKiw+qLTnORbo2dxFdm0uv5GT0rJnCzJfK3X46QSMwewuPXg="
