sudo: required
addons:
  apt:
    update: true
    packages:
      - docker-ce
services:
  - docker
script:
  - export DOCKER_CLI_EXPERIMENTAL=enabled
  - source sha_functions.sh
#  - node_x86_sha=$(get_tag_sha "balenalib/amd64-alpine-node" "latest")
  - node_x86_sha=$(get_tag_sha "amd64/node" "alpine3.12")
  - echo $node_x86_sha
  - treehouses_node_x86_sha=$(get_manifest_sha "treehouses/node" "amd64")
  - echo $treehouses_node_x86_sha
  - node_arm_sha=$(get_tag_sha "balenalib/raspberry-pi-alpine-node" "latest")
  - echo $node_arm_sha
  - treehouses_node_arm_sha=$(get_manifest_sha "treehouses/node" "arm")
  - echo $treehouses_node_arm_sha
  - node_arm64_sha=$(get_tag_sha "balenalib/raspberrypi4-64-node" "latest")
  - echo $node_arm64_sha
  - treehouses_node_arm64_sha=$(get_manifest_sha "treehouses/node" "arm64")
  - echo $treehouses_node_arm64_sha
  - flag=$(compare_sha "$node_x86_sha" "$treehouses_node_x86_sha" "$node_arm_sha" "$treehouses_node_arm_sha" "$node_arm64_sha" "$treehouses_node_arm64_sha")
  - echo $flag
  - echo $DOCKERAPIKEY | docker login -u "sevenseas" --password-stdin
before_deploy:
  - tag="3.12-$(date +%Y%m%d%H%M)"
  - echo $tag
#  - create_manifests treehouses/node $tag  "balenalib/amd64-alpine-node@"$node_x86_sha "balenalib/raspberry-pi-alpine-node@"$node_arm_sha "balenalib/raspberrypi4-64-node@"$node_arm64_sha
  - create_manifests treehouses/node $tag  "amd64/node@"$node_x86_sha "balenalib/raspberry-pi-alpine-node@"$node_arm_sha "balenalib/raspberrypi4-64-node@"$node_arm64_sha
  - docker manifest inspect treehouses/node:latest
  - docker manifest inspect treehouses/node:$tag
deploy:
  - provider: script
    script: docker manifest push treehouses/node:latest; docker manifest push treehouses/node:$tag
    skip_cleanup: true
    on:
      all_branches: true
      condition: $flag = true
env:
  global:
    secure: "INhtJAsjlI8wD0rAv1iwe+qspTv+QZoSmMJwpdItf7Xg64g/u+P7wTcH5KS2IK4G3gyd4aJf6l9Blqp7simLu2yWWIK80ZYe+TAwmCvvuroynYve1eMzziaaly/A9cxVfgtaZADvCT/DRFhWLKwqfVFIppGpJwliWo3KJntIuvTGlUzj2KGS6vPmiPLy2emcgooluS8Xi8PN7oLlsJtzSl/nr5g4ZONoEQF1pCIhWO96oNAWIRu5WjzcLAaF3f7EeX3pxD6B2b5ElQiDJQVEfXy977nNeK1vFeaqueGkgVy80cJlPYhh0JrdyhXUAma5Qhm1gXDBkRL5mdqO2YA7jhrlJVPMH5VT7BwTL1zkDoLXahllmgkUIpPRg+zj8VCmcUMZSBXeuwNWYMFO+mszIsw89WnEK78LyBnQuwtrZcHlSIM7yn+hc+1IdqQ9ijDe6z7mim/tZLQ10lHivhS67OU/Oo3dGLIsHxB21zwjyeTRZUi4DgCTnMdNrl4mV56YloTCuwJTTw8pqj/8Vo386pyHUPvYbs6UbvnSVYzwDaLQldbDIfsRI7dp2VvSqoPuzsAXblkw8Dz4wn/sTVyQB8JUziSj+Nwv4046GEy31dVjQ1/mo3kGTE2WnINa7RscxJicIFV4pmdWhwHvteMC4jwevTUbrIaW916ZBJfdxZE="
