sudo: required
addons:
  apt:
    update: true
    packages:
      - docker-ce
services:
  - docker
script:
  - export DOCKER_CLI_EXPERIMENTAL=enabled
  - source utils.sh
  - flag_arm=$(compare "treehouses/alpine:latest" "treehouses/node:latest" "arm")
  - flag_arm64=$(compare "treehouses/alpine:latest" "treehouses/node:latest" "arm64")
  - flag_amd64=$(compare "treehouses/alpine:latest" "treehouses/node:latest" "amd64")
  - echo $DOCKERAPIKEY | docker login -u "sevenseas" --password-stdin
  - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
  - build_image "treehouses/alpine:latest" arm "treehouses/node" $flag_arm
  - build_image "treehouses/alpine:latest" arm64 "treehouses/node" $flag_arm64
  - build_image "treehouses/alpine:latest" amd64 "treehouses/node" $flag_amd64
  - flag=$(change $flag_arm $flag_arm64 $flag_amd64)
  #- flag="true"
  - echo $flag
before_deploy:
  - deploy_image "treehouses/node" arm
  - deploy_image "treehouses/node" arm64
  - deploy_image "treehouses/node" amd64
  - tag1="latest"
  - tag2=$(date +%Y%m%d%H%M)
  - echo $tag2
  - create_manifests treehouses/node $tag1 $tag2 treehouses/node-tags:amd64 treehouses/node-tags:arm treehouses/node-tags:arm64
  - docker manifest inspect treehouses/node:$tag1
  - docker manifest inspect treehouses/node:$tag2
deploy:
  - provider: script
    script: docker manifest push treehouses/node:$tag1; docker manifest push treehouses/node:$tag2
    skip_cleanup: true
    on:
      all_branches: true
      condition: "$flag = true"
env:
  global:
    - secure: INhtJAsjlI8wD0rAv1iwe+qspTv+QZoSmMJwpdItf7Xg64g/u+P7wTcH5KS2IK4G3gyd4aJf6l9Blqp7simLu2yWWIK80ZYe+TAwmCvvuroynYve1eMzziaaly/A9cxVfgtaZADvCT/DRFhWLKwqfVFIppGpJwliWo3KJntIuvTGlUzj2KGS6vPmiPLy2emcgooluS8Xi8PN7oLlsJtzSl/nr5g4ZONoEQF1pCIhWO96oNAWIRu5WjzcLAaF3f7EeX3pxD6B2b5ElQiDJQVEfXy977nNeK1vFeaqueGkgVy80cJlPYhh0JrdyhXUAma5Qhm1gXDBkRL5mdqO2YA7jhrlJVPMH5VT7BwTL1zkDoLXahllmgkUIpPRg+zj8VCmcUMZSBXeuwNWYMFO+mszIsw89WnEK78LyBnQuwtrZcHlSIM7yn+hc+1IdqQ9ijDe6z7mim/tZLQ10lHivhS67OU/Oo3dGLIsHxB21zwjyeTRZUi4DgCTnMdNrl4mV56YloTCuwJTTw8pqj/8Vo386pyHUPvYbs6UbvnSVYzwDaLQldbDIfsRI7dp2VvSqoPuzsAXblkw8Dz4wn/sTVyQB8JUziSj+Nwv4046GEy31dVjQ1/mo3kGTE2WnINa7RscxJicIFV4pmdWhwHvteMC4jwevTUbrIaW916ZBJfdxZE=
