name: node

on: [push]

jobs:
  build-deploy-node:
    runs-on: ubuntu-20.04
    steps:
      - name: login to docker
        run: docker login -u ${{ secrets.DOCKERUSERNAME }} -p ${{ secrets.DOCKERAPIKEY }}
      - name: building node and deploying to docker
        run: |
          export DOCKER_CLI_EXPERIMENTAL=enabled
          repo="rjpadilla/node"
          source utils.sh
          alpine_arm_sha=$(get_manifest_sha "treehouses/alpine:latest" "arm")
          echo "alpine arm"
          echo $alpine_arm_sha
          node_arm_sha=$(get_manifest_sha "node:latest" "arm")
          echo "node arm"
          echo $node_arm_sha
          flag_arm=$(is_base "treehouses/alpine@"$alpine_arm_sha "node@"$node_arm_sha)
          echo "flag arm"
          echo $flag_arm
          alpine_amd64_sha=$(get_manifest_sha "treehouses/alpine:latest" "amd64")
          echo $alpine_amd64_sha
          node_amd64_sha=$(get_manifest_sha "node:latest" "amd64")
          echo $node_amd64_sha
          flag_amd64=$(is_base "treehouses/alpine@"$alpine_amd64_sha "node@"$node_amd64_sha)
          echo "flag amd64"
          echo $flag_amd64
          alpine_arm64_sha=$(get_manifest_sha "treehouses/alpine:latest" "arm64")
          echo "alpine arm64"
          echo $alpine_arm64_sha
          node_arm64_sha=$(get_manifest_sha "node:latest" "arm64")
          echo "node arm64"
          echo $node_arm64_sha
          flag_arm64=$(is_base "treehouses/alpine@"$alpine_arm64_sha "node@"$node_arm64_sha)
          echo "flag arm64"
          echo $flag_arm64
          version2=$(image_version node:latest)
          echo "repo version is $version2"
          docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
          build_image "treehouses/alpine:latest" arm "$repo"
          build_image "treehouses/alpine:latest" amd64 "$repo"
          build_image "treehouses/alpine:latest" arm64 "$repo"
          flag=$(compare "treehouses/alpine@"$alpine_arm_sha "node@"$node_arm_sha "treehouses/alpine@"$alpine_amd64_sha "node@"$node_amd64_sha "treehouses/alpine@"$alpine_arm64_sha "node@"$node_arm64_sha "node" "node-tags:amd64")
          echo $flag
          deploy_image "$repo" arm
          deploy_image "$repo" amd64
          deploy_image "$repo" arm64
          tag=$(date +%Y%m%d%H%M)
          tag2="latest"
          echo $tag
          create_manifest $repo $tag $tag2 $repo-tags:amd64 $repo-tags:arm $repo-tags:arm64
          docker manifest inspect $repo:$tag
          docker manifest inspect $repo:$tag2
          if [[ $flag == true ]]; then
            docker manifest push $repo:$tag; docker manifest push $repo:$tag2
          else
            echo "no changes"
          fi