name: node

on: [push]

jobs:
  build-deploy-node:
    runs-on: ubuntu-20.04
    steps:
      - name: login to docker
        run: docker login -u ${{ secrets.DOCKERUSERNAME }} -p ${{ secrets.DOCKERAPIKEY }}
      - name: building node and deploying to docker
        run: |
          export DOCKER_CLI_EXPERIMENTAL=enabled
          echo test